"""Build one additive race patch from the validated individual patch records."""
import copy, hashlib, json, sys, zipfile
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT/'tools/vendor'))
import kenshi
SOURCE = ROOT/'qa/distribution_zip_20260915/420_Smoking_Optional_Race_Patches_candidate/optional'
NAME = '420_Races'
OUT = ROOT/'build'/NAME
OUT.mkdir(exist_ok=True)
records, animations, manifests = {}, {}, []
for folder in sorted(SOURCE.iterdir()):
    if not folder.is_dir(): continue
    manifest = json.loads((folder/'patch_manifest.json').read_text(encoding='utf-8-sig'))
    manifests.append(manifest)
    reader = kenshi.ModFileReader(folder/(folder.name+'.mod'))
    try:
        mapping = {}
        for sid, record in reader.records.items():
            if record['type'] != 'BASE_ANIMATIONS': continue
            signature = json.dumps(record['fields'], sort_keys=True)
            if signature not in animations:
                new_id = f'{len(animations)+1}-{NAME}.mod'
                animations[signature] = new_id
                records[new_id] = copy.deepcopy(record)
                records[new_id]['name'] = f'420 Race animations {len(animations)}'
            mapping[sid] = animations[signature]
        for sid, record in reader.records.items():
            if record['type'] != 'RACE': continue
            assert record['datatype'] == 'CHANGED'
            assert all(not v for v in record['fields'].values())
            assert set(record['extra']) == {'animation files'}
            assert not record['instances']
            result = copy.deepcopy(record)
            result['extra']['animation files'] = {mapping[k]:v for k,v in record['extra']['animation files'].items()}
            if sid in records:
                assert records[sid] == result, f'Conflicting race: {sid}'
            records[sid] = result
    finally:
        reader.handle.close()
race_records = {k:r for k,r in records.items() if r['type']=='RACE'}
table = ['// SPDX-License-Identifier: GPL-3.0-or-later', '// Generated by tools/build_unified_race_patch.py; do not edit.', 'static const RacePatchEntry kRacePatches[] = {']
for sid, record in sorted(race_records.items()):
    refs = list(record['extra']['animation files'])
    assert len(refs) == 2
    table.append('    {' + ', '.join(json.dumps(v) for v in [sid]+refs) + '},')
table.append('};')
(ROOT/'src/re_smoke/RacePatchTable.h').write_text('\n'.join(table)+'\n', encoding='utf-8')
records = {k:r for k,r in records.items() if r['type']=='BASE_ANIMATIONS'}
dependencies = 'gamedata.base,Newwworld.mod,rebirth.mod,420_Smoking.mod,420_Smoking_RE.mod'
writer = kenshi.ModFileWriter(OUT/(NAME+'.mod'), 1, 'dayama74b', 'Combined smoking animation references for supported custom humanoid races.', dependencies, '')
writer.records(records)
writer.handle.close()
reader = kenshi.ModFileReader(OUT/(NAME+'.mod'))
assert reader.records == records
assert len(race_records) == 59
assert not any(r['type']=='RACE' for r in reader.records.values())
assert all('Patch_' not in k for r in records.values() for refs in r['extra'].values() for k in refs)
reader.handle.close()
(OUT/'patch_manifest.json').write_text(json.dumps({'name':NAME,'race_count':59,'source_patch_count':17,'animation_profiles':len(animations),'sources':manifests},indent=2),encoding='utf-8')
(OUT/'RE_Kenshi.json').write_text(json.dumps({'Plugins':['SmokingRaces.dll']},indent=2),encoding='utf-8')
configuration = []
for manifest in manifests:
    for race in manifest['included']:
        configuration.append({'id':race['id'], 'profile':'_'.join(race['profile'])})
assert len(configuration)==59
for row in configuration:
    expected={'female_female':[1,2], 'male_female':[3,4], 'male_male':[5,6]}[row['profile']]
    assert set(race_records[row['id']]['extra']['animation files']) == {f'{n}-420_Races.mod' for n in expected}
(OUT/'Races.json').write_text(json.dumps({'version':1,'races':configuration},indent=2),encoding='utf-8')
print(f'Built {NAME}: zero race records, {len(animations)} shared animation records, 59 runtime lookup entries.')
